name: Export Exercise Material
run-name: ${{ github.actor }} is exporting SnarkJS exercises ðŸš€
on:
  workflow_dispatch:
  push:
     branches:
       - master

jobs:
  run-export-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # required for accessing files in repository.

      - name: Export Part I
        run: bash export.sh 1
      - name: 'Upload Artifact Part I'
        uses: actions/upload-artifact@v4
        with:
          name: snarkjs_part_1.zip
          path: snarkjs_part_1.zip

      - name: Export Part I
        run: bash export.sh 2
      - name: 'Upload Artifact Part II'
        uses: actions/upload-artifact@v4
        with:
          name: snarkjs_part_2.zip
          path: snarkjs_part_2.zip

      - name: Export Part I
        run: bash export.sh 3
      - name: 'Upload Artifact Part III'
        uses: actions/upload-artifact@v4
        with:
          name: snarkjs_part_3.zip
          path: snarkjs_part_3.zip
